Update algorithm for parsing #1274
pkkid/python-plexapi pull request #1276
Opened 2023-10-20 15:31 UTC by Dr-Blank

## Description

algorithm for parsing is updated to cover multilevel filter groups parsing

Fixes
- https://github.com/pkkid/python-plexapi/issues/1274

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

2023-10-22 05:31 UTC, JonnyWong16 commented
Thanks. Could you add some tests with some more complex filters? Right now the tests only check that searching with the parsed filters returns the same items.

https://github.com/pkkid/python-plexapi/blob/e44939c426e9c050e8cfc7915c4ac4dca42b8ad1/tests/test_collection.py#L278-L279

https://github.com/pkkid/python-plexapi/blob/e44939c426e9c050e8cfc7915c4ac4dca42b8ad1/tests/test_playlist.py#L198-L200

The new tests should actually check that the filter and parsed filter dictionaries are equal.

```py
parsedFilters = collection.filters()
assert filters == parsedFilters
```
```py
parsedFilters = playlist.filters()
assert filters == parsedFilters
```

2023-10-22 23:45 UTC, Dr-Blank commented
> Thanks. Could you add some tests with some more complex filters? Right now the tests only check that searching with the parsed filters returns the same items.

Could you please guide me to a document where I can learn how to setup plex environment for testing?

Currently running test locally fails all of them except a few. I have to use GH Actions every time, and it would be great to have it run locally.

I know it sets up pms using docker but if there was a script for this to do automatically?

2023-10-23 00:01 UTC, JonnyWong16 commented
See Discord.

2023-10-25 10:46 UTC, Dr-Blank commented
@JonnyWong16

I have added 2 tests which will fail for the old algorithm that are [passing](https://github.com/Dr-Blank/python-plexapi/actions/runs/6639213555) for this PR.

2023-11-05 18:36 UTC, JonnyWong16 requested changes
The logic looks good. Thanks!

Just a few stylistic changes.

2023-11-05 18:36 UTC, JonnyWong16 commented on plexapi/mixins.py
> +        """parse filter groups from input lines between push and pop"""
```suggestion
        """ Parse filter groups from input lines between push and pop. """
```

2023-11-05 18:36 UTC, JonnyWong16 commented on plexapi/mixins.py
> +        """parse the query string into a dict"""
```suggestion
        """ Parse the query string into a dict. """
```

2023-11-05 18:36 UTC, JonnyWong16 commented on plexapi/mixins.py
> +        integer_keys = set(("includeGuids", "limit"))
```suggestion
        special_keys = {"type", "sort"}
        integer_keys = {"includeGuids", "limit"}
```

2023-11-05 18:36 UTC, JonnyWong16 commented on plexapi/mixins.py
> +        """Parse the content string and returns the filter dict."""
```suggestion
        """ Parse the content string and returns the filter dict. """
```

2023-11-05 23:41 UTC, JonnyWong16 approved these changes

2023-11-06 00:23 UTC, merged