Feature: Add source property to Video
pkkid/python-plexapi pull request #1335
Opened 2024-01-08 02:00 UTC by glensc

## Description

A Playlist entry if added a remote server item has field "source" initialized with value like `server://<server_id>/com.plexapp.plugins.library`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

2024-01-08 02:06 UTC, glensc commented
here's diff of keys local vs remote playlist entries. i guess some fields like titleSort rather vary on whether item has sort title set.

```diff
--- pl-local-keys.json    2024-01-08 03:38:13
+++ pl-remote-keys.json    2024-01-08 03:38:28
@@ -6,17 +6,17 @@
   "duration",
   "guid",
   "key",
-  "librarySectionID", // local
-  "librarySectionKey", // local
-  "librarySectionTitle", // local
+  "originalTitle", // remote
   "originallyAvailableAt",
   "playlistItemID",
   "ratingKey",
+  "source", // remote
   "studio",
   "summary",
+  "tagline", // remote
   "thumb",
   "title",
+  "titleSort", // remote
   "type",
-  "updatedAt", // local
   "year"
 ]
```

2024-01-08 19:30 UTC, glensc commented
This is unforunate, this seems to conflict with History object:

```
  File "/home/runner/work/python-plexapi/python-plexapi/tests/test_history.py", line 93, in test_history_PlexHistory
    assert hist.source() == movie
TypeError: 'NoneType' object is not callable
```
- https://github.com/pkkid/python-plexapi/actions/runs/7442362354/job/20245688665?pr=1335#step:12:793

as apparently `History` extends from `Movie` object (`class MovieHistory(PlexHistory, Movie):`
- https://github.com/pkkid/python-plexapi/pull/1185

2024-01-08 22:22 UTC, JonnyWong16 commented
What is a "remote playlist entry"? Do you mean on someone else's server? What is the Plex URL endpoint where we can see this `source` attribute?

2024-01-09 12:17 UTC, glensc commented
Remote playlist is when you add item to playlist, but choose different server.

<img width="475" alt="image" src="https://github.com/pkkid/python-plexapi/assets/199095/3a230a25-f02d-4fbd-a444-cba51146d557">

This seems to be available only when I'm on server that I don't own, and have at least one server that I own.

the `source` attribute is seen with the existing get playlist api call:

```py
        p = server.playlist("Playlist Name")
        source = p._data.attrib.get("source")
```

so,  `http://localhost:32400/playlists/<ratingKey>/items`

2024-01-09 18:04 UTC, JonnyWong16 commented
The `source` attribute should be on `Movie`, `Episode`, `Track`, and `Photo`.

I need to think about what to do about the conflicting `PlexSession.source()` and `PlexHistory.source()` methods.

2024-01-14 21:54 UTC, glensc commented
Added to Track c4c2d03 and Photo b439ea8

2024-01-14 21:58 UTC, glensc commented
maybe add this new property with the name "remote_source"?

2024-02-10 17:33 UTC, JonnyWong16 commented
I think we name the attribute `sourceURI` and don't change the methods.

References:

https://github.com/pkkid/python-plexapi/blob/b51aa1924b5b28ba61aefbb4162aff6e6864561b/plexapi/server.py#L172-L173

https://github.com/pkkid/python-plexapi/blob/b51aa1924b5b28ba61aefbb4162aff6e6864561b/plexapi/playqueue.py#L27

2024-02-11 16:23 UTC, glensc commented
Updated: 3d7fd9e215861715d871c81cc80fca100be97462

2024-02-11 16:45 UTC, JonnyWong16 requested changes

2024-02-11 16:45 UTC, JonnyWong16 commented on plexapi/audio.py
> +            sourceURI (str): Remote server URL (server://<server_id>/com.plexapp.plugins.library) (remote playlist item only)
```suggestion
            sourceURI (str): Remote server URI (server://<machineIdentifier>/com.plexapp.plugins.library) (remote playlist item only)
```

2024-02-11 16:45 UTC, JonnyWong16 commented on plexapi/photo.py
> +            sourceURI (str): Remote server URL (server://<server_id>/com.plexapp.plugins.library) (remote playlist item only)
```suggestion
            sourceURI (str): Remote server URI (server://<machineIdentifier>/com.plexapp.plugins.library) (remote playlist item only)
```

2024-02-11 16:45 UTC, JonnyWong16 commented on plexapi/video.py
> +            sourceURI (str): Remote server URL (server://<server_id>/com.plexapp.plugins.library) (remote playlist item only)
```suggestion
            sourceURI (str): Remote server URI (server://<machineIdentifier>/com.plexapp.plugins.library) (remote playlist item only)
```

2024-02-11 16:45 UTC, JonnyWong16 commented on plexapi/video.py
> +            sourceURI (str): Remote server URL (server://<server_id>/com.plexapp.plugins.library) (remote playlist item only)
```suggestion
            sourceURI (str): Remote server URI (server://<machineIdentifier>/com.plexapp.plugins.library) (remote playlist item only)
```

2024-02-11 16:55 UTC, glensc commented
no longer breaking change label

2024-02-11 17:01 UTC, JonnyWong16 approved these changes

2024-02-17 22:16 UTC, merged