Fix: Disallow using smart playlist with items
pkkid/python-plexapi pull request #1377
Opened 2024-02-26 21:05 UTC by glensc

## Description

Fixes https://github.com/pkkid/python-plexapi/issues/1375

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable

2024-02-26 21:09 UTC, glensc commented
actually, i'm not sure what was happening. as the "items" doesn't seem to be passed to the `_createSmart` method

2024-02-26 21:26 UTC, glensc commented
so, what was happening was that it called this URL:

- `/playlists?smart=1&title=The Melchior Collection&type=video&uri=server://[redacted]/com.plexapp.plugins.library/library/sections/1/all?includeGuids=1&type=1`


which seems like smart playlist with no filters (so it contains whole library)

2024-02-27 08:44 UTC, glensc commented
Maybe what could be done here instead is to raise an error if no filters are provided

2024-02-29 11:12 UTC, glensc commented
So the change here should be fine. It would disallow using smart and items, possibly not confusing the user. 

user can still create smart playlist without filters as long as they don't also pass items.

2024-03-01 05:55 UTC, JonnyWong16 requested changes
Could you also add the same exception for smart collections?

https://github.com/pkkid/python-plexapi/blob/abcab4f78d22e86b380327c6014d3148e0248e6d/plexapi/collection.py#L505-L506

2024-03-01 05:55 UTC, JonnyWong16 commented on plexapi/playlist.py
> +                raise BadRequest('Cannot fill items for a smart playlist.')
```suggestion
                raise BadRequest('Cannot create a smart playlist with items.')
```

2024-03-03 07:13 UTC, JonnyWong16 approved these changes

2024-03-16 22:17 UTC, merged