Added AdvancedSettingsMixin
pkkid/python-plexapi pull request #714
Opened 2021-03-27 16:07 UTC by meisnate12

## Description

I moved preferences, editAdvanced, and defaultAdvanced methods from video.Show in a new mixin called AdvancedSettingsMixin and added the mixin to video.Show, video.Movie, and audio.Artist

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update (I'm not sure if the docs would need an update or not)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods
- [ ] I have added tests when applicable (I could use some help writing proper tests for this)

2021-03-27 17:34 UTC, Hellowlol commented
Hi! Remember to test your changes. This will fail. Check the flake output 🙂

2021-03-27 19:21 UTC, JonnyWong16 requested changes

2021-03-27 19:21 UTC, JonnyWong16 commented on plexapi/audio.py
> +        CollectionMixin, CountryMixin, GenreMixin, MoodMixin, SimilarArtistMixin, StyleMixin, AdvancedSettingsMixin):
Let's keep the order of the Mixins. Put `AdvancedSettingsMixin` before `ArtMixin`.

2021-03-27 19:21 UTC, JonnyWong16 commented on plexapi/video.py
> +class Movie(Video, Playable, ArtMixin, PosterMixin, SplitMergeMixin, UnmatchMatchMixin, AdvancedSettingsMixin,
Same `AdvancedSettingsMixin` before `ArtMixin`.

2021-03-27 19:21 UTC, JonnyWong16 commented on plexapi/video.py
> +        CollectionMixin, GenreMixin, LabelMixin, AdvancedSettingsMixin):
Same `AdvancedSettingsMixin` before `ArtMixin`.

2021-03-27 21:53 UTC, JonnyWong16 approved these changes

2021-04-05 20:14 UTC, JonnyWong16 commented
Tests added. Ready to merge.

2021-04-05 20:44 UTC, merged