added collection visibility
pkkid/python-plexapi pull request #785
Opened 2021-06-30 12:23 UTC by meisnate12

## Description

Added methods to get collection visibility and to be able to set the collection's visibility 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the docstring for new or existing methods

2021-07-02 17:17 UTC, JonnyWong16 requested changes

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +    def visibilities(self):
This method would return a `HubManage` object for the collection.

```python
key = '/hubs/sections/%s/manage?metadataItemId=%s' % (self.section().key, self.ratingKey)
data = self._server.query(key)
try:
    return self.findItems(data, cls=HubManage)[0]
except IndexError:
    psss  # or raise NotFound?
```
No need to cache it.

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +    def visibleLibrary(self):
These properties won't be needed with `HubManage()` object.

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +    def visibleUpdate(self, library=None, home=None, shared=None):
This method would be part of the `HubManage()` object, similar to `~plexapi.myplex.AccountOptOut()`.

https://github.com/pkkid/python-plexapi/blob/master/plexapi/myplex.py#L1354-L1386

```python
def _updateVisibility(self, recommended=None, home=None, shared=None):
     # See comments below

def promoteRecommended(self):
    self._updateVisibility(recommended=True)

def promoteHome(self):
    self._updateVisibility(home=True)

def promoteShared(self):
    self._updateVisibility(shared=True)
```

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +        if library is None and home is None and shared is None:
No need to check for `None`. The request can go through without changing anything.

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +        key = '/hubs/sections/%s/manage?metadataItemId=%s' % (self.section().key, self.ratingKey)
Use `args` so you can add each parameter below.
```python
args = {'metadataItemId': self.ratingKey}
```

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +        promote = (library is None and self.visibleLibrary) or library
Just check if each parameter `is not None` and add to `args`. You don't need to include all three options.
```python
if recommended is not None:
    args['promotedToRecommended'] = int(recommended)
```

2021-07-02 17:17 UTC, JonnyWong16 commented on plexapi/collection.py
> +
Join `args` with `key` using `joinArgs`.
```python
key = '/hubs/sections/%s/manage%s' % (self.section().key, utils.joinArgs(args))
```

2021-07-02 17:26 UTC, JonnyWong16 commented
Test should be added.

2021-07-02 17:41 UTC, meisnate12 commented
Thanks for all the feedback I'll dive into this over the weekend and make all the changes you requested

2022-07-22 15:27 UTC, meisnate12 commented
@JonnyWong16 Updated with your changes and added the ability to grab/reset all managed hubs. I attempted to add some tests for collection visibility but the test is just getting a Not Found Response `plexapi.exceptions.NotFound: (404) not_found; http://127.0.0.1:32400/hubs/sections/1/manage?metadataItemId=86 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>` 

The only way I was able to get a 404 Not Found Response if i give the url an invalid section ID which should be acquired automatically by the module. Im not realyl sure what to do to fix the test and i was hoping you had some insight

2022-07-22 15:43 UTC, JonnyWong16 commented
It might be because collection visibility option require Plex Pass so it will fail for the unclaimed tests.

1. Add another unclaimed test using one of the standard manage hubs (like Recently Added).
2. Mark your collection test with `@pytest.mark.authenticated` so it will only run during the claimed tests which has Plex Pass.

2022-07-31 20:35 UTC, JonnyWong16 requested changes
Sorry for so many comments.

I made a git patch with all the changes here:
https://gist.github.com/JonnyWong16/c50191c14f457536b1d19ac5ef8e2ccf

Or I can apply the patch if you want.

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +class HubManage(PlexObject):
I think renaming to `ManagedHub` sounds better.
```suggestion
class ManagedHub(PlexObject):
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        Attributes:
Add
```suggestion
        Attributes:
            TAG (str): 'Hub'
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +
```suggestion
    TAG = 'Hub'

```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        self._collection_key = None
```suggestion
        self._promoted = True  # flag to indicate if this hub has been promoted on the list of managed recommendations
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        self._librarySectionID = parent.key if isinstance(parent, LibrarySection) else parent.librarySectionID
```suggestion
        self.librarySectionID = parent.key if isinstance(parent, LibrarySection) else parent.librarySectionID
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +
Add `reload()` method.
```suggestion
    def reload(self):
        """ Reload the data for this managed hub. """
        key = f'/hubs/sections/{self.librarySectionID}/manage'
        hub = self.fetchItem(key, self.__class__, identifier=self.identifier)
        self.__dict__.update(hub.__dict__)
        return self

```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        if not self.identifier:
```suggestion
        if not self._promoted:
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        if not self.identifier:
```suggestion
        if not self._promoted:
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/library.py
> +        self.updateVisibility(recommended=True)
Add `return` to each method to allow method chaining.
```suggestion
        return self.updateVisibility(recommended=True)
```

2022-07-31 20:35 UTC, JonnyWong16 commented on plexapi/collection.py
> +            return hub
We can set the `identifier`, `title`, and `_promoted` flag for an unmanaged collection.
```suggestion
        key = f'/hubs/sections/{self.librarySectionID}/manage?metadataItemId={self.ratingKey}'
        data = self._server.query(key)
        hub = self.findItem(data, cls=ManagedHub)
        if hub is None:
            hub = ManagedHub(self._server, data, parent=self)
            hub.identifier = f'custom.collection.{self.librarySectionID}.{self.ratingKey}'
            hub.title = self.title
            hub._promoted = False
        return hub
```

2022-07-31 20:42 UTC, JonnyWong16 commented
It looks like unclaimed servers do not have recommendations at all, so the library test also needs to be marked as authenticated.

![image](https://user-images.githubusercontent.com/9099342/182044570-f0d7ac30-9106-4dc5-8796-59aca5b6a477.png)

2022-08-01 15:01 UTC, meisnate12 commented
i dont mind all the comments at all. All your updates should be in and the tests have passed let me know if you need me to do anything else.

2022-08-01 18:16 UTC, JonnyWong16 requested changes
Just some minor comments for tests.

2022-08-01 18:16 UTC, JonnyWong16 commented on plexapi/library.py
> +                    managedHib.promoteRecommended().promoteHome().demoteShared().reload()
Typo
```suggestion
                    managedHub.promoteRecommended().promoteHome().demoteShared().reload()
```

2022-08-01 18:16 UTC, JonnyWong16 commented on tests/test_collection.py
> +    visibility.updateVisibility(recommended=True, home=True, shared=True)
Needs reload.
```suggestion
    visibility.updateVisibility(recommended=True, home=True, shared=True).reload()
```

2022-08-01 18:16 UTC, JonnyWong16 commented on tests/test_collection.py
> +    visibility.updateVisibility(recommended=False, home=False, shared=False)
Needs reload.
```suggestion
    visibility.updateVisibility(recommended=False, home=False, shared=False).reload()
```

2022-08-01 18:16 UTC, JonnyWong16 commented on tests/test_collection.py
> +    with pytest.raises(BadRequest):
Actually raises `NotFound`.
```suggestion
    with pytest.raises(NotFound):
```

2022-08-01 18:16 UTC, JonnyWong16 commented on tests/test_library.py
> +    last.move()
Test the `after` parameter works as well.

2022-08-01 18:16 UTC, JonnyWong16 commented on tests/test_library.py
> +    assert last.identifier == recommendations[0].identifier
Test all the individual `promote*()` and `demote*()` methods as well.

2022-08-04 23:54 UTC, JonnyWong16 requested changes

2022-08-04 23:54 UTC, JonnyWong16 commented on tests/test_collection.py
> +    with pytest.raises(NotFound):
This one was correct with `BadRequest`.
```suggestion
    with pytest.raises(BadRequest):
```

2022-08-04 23:54 UTC, JonnyWong16 commented on tests/test_collection.py
> +    assert visibility.promotedToSharedHome is False
I want to move these to the library tests so that we also cover testing promoting/demoting the standard library hubs.

2022-08-05 02:51 UTC, meisnate12 commented
let me know if theres any more changes you need me to make

2022-08-05 03:34 UTC, JonnyWong16 commented
Looks good!

2022-08-05 03:35 UTC, JonnyWong16 approved these changes

2022-08-06 02:32 UTC, JonnyWong16 requested changes
I ran the `test_library_MovieSection_managedHubs` test locally and it was failing. I found out that you need to provide all three parameters (`promotedToRecommended`, `promotedToOwnHome`, and `promotedToSharedHome`) in the API call to update the visibility managed hubs, even if you don't change them. Currently `updateVisibility()` only provides the parameters that change instead of all three. This also means the `updateVisibility()` needs to automatically `reload()` the hub so that the default attributes get updated if the method is called again/chained.

2022-08-06 02:32 UTC, JonnyWong16 commented on plexapi/library.py
> +        params = {}
Changing the visibility of the default library hubs actually fails unless all three parameters are provided. Set the default parameters to the current attribute values.
```suggestion
        params = {
            'promotedToRecommended': int(self.promotedToRecommended),
            'promotedToOwnHome': int(self.promotedToOwnHome),
            'promotedToSharedHome': int(self.promotedToSharedHome),
        }
```

2022-08-06 02:32 UTC, JonnyWong16 commented on plexapi/library.py
> +        return self
Need to automatically reload so that the current attribute values get updated.
```suggestion
        return self.reload()
```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_collection.py
2 blank lines before function.
```suggestion


```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_collection.py
2 blank lines after function
```suggestion


```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_library.py
> +    first.promoteRecommended().promoteHome().prmoteShared().reload()
Typo and remove reload.
```suggestion
    first.promoteRecommended().promoteHome().promoteShared()
```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_library.py
> +    first.demoteRecommended().demoteHome().demoteShared().reload()
Remove reload.
```suggestion
    first.demoteRecommended().demoteHome().demoteShared()
```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_library.py
> +    movies.resetManagedHubs()
Need to get the recommendations again.
```suggestion
    movies.resetManagedHubs()
    recommendations = movies.managedHubs()
```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_collection.py
> +    visibility.updateVisibility(recommended=True, home=True, shared=True).reload()
Remove reload.
```suggestion
    visibility.updateVisibility(recommended=True, home=True, shared=True)
```

2022-08-06 02:32 UTC, JonnyWong16 commented on tests/test_collection.py
> +    visibility.updateVisibility(recommended=False, home=False, shared=False).reload()
Remove reload.
```suggestion
    visibility.updateVisibility(recommended=False, home=False, shared=False)
```

2022-08-26 17:43 UTC, JonnyWong16 approved these changes

2022-08-26 17:43 UTC, merged